version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm-check-updates
    versions:
    - 11.5.1
    - 11.5.3
    - 11.5.4
    - 11.5.5
    - 11.5.6
  - dependency-name: documentation
    versions:
    - 13.2.4
  - dependency-name: "@babel/core"
    versions:
    - 7.13.16
  commit-message:
    prefix: chore
    include: scope
